# Generated by Django 4.1.7 on 2023-05-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_carreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEALER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('nip', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=250)),
                ('bank', models.CharField(max_length=250)),
                ('bank_account', models.CharField(max_length=250)),
            ],
        ),
    ]
