# Generated by Django 4.1.7 on 2023-04-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Marka')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('year', models.IntegerField(verbose_name='Rok produkcji')),
                ('price', models.IntegerField(verbose_name='Cena (PLN)')),
                ('mileage', models.IntegerField(verbose_name='Przebieg (km)')),
                ('description', models.TextField(verbose_name='Opis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Zdjęcia')),
            ],
        ),
        migrations.CreateModel(
            name='CarFuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=50, verbose_name='Rodzaj paliwa')),
            ],
        ),
        migrations.CreateModel(
            name='CarGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear', models.CharField(max_length=50, verbose_name='Skrzynia biegów')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Imię i nazwisko / Nazwa firmy')),
                ('pesel', models.IntegerField(blank=True, null=True, verbose_name='PESEL')),
                ('nip', models.IntegerField(blank=True, null=True, verbose_name='NIP')),
                ('adress', models.CharField(max_length=100, verbose_name='Adres')),
                ('city', models.CharField(max_length=50, verbose_name='Miasto')),
                ('zip', models.IntegerField(verbose_name='Kod pocztowy')),
                ('phone', models.IntegerField(verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Imię i nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Wiadomość')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Imię i nazwisko')),
                ('adress', models.CharField(max_length=100, verbose_name='Adres')),
                ('city', models.CharField(max_length=50, verbose_name='Miasto')),
                ('zip', models.IntegerField(verbose_name='Kod pocztowy')),
                ('phone', models.IntegerField(verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('position', models.CharField(max_length=50, verbose_name='Stanowisko')),
                ('hire_date', models.DateField(verbose_name='Data zatrudnienia')),
                ('fire_date', models.DateField(blank=True, null=True, verbose_name='Data zwolnienia')),
            ],
        ),
        migrations.CreateModel(
            name='Order_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(verbose_name='Data transakcji')),
                ('order_price', models.IntegerField(verbose_name='Kwota transakcji')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clients')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order_status')),
            ],
        ),
    ]
