# Generated by Django 4.1.7 on 2023-04-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_car_engine_capacity_car_engine_power_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Marka')),
            ],
        ),
    ]
