# Generated by Django 4.1.7 on 2023-03-31 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_clients_employee_alter_car_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='Numer transakcji')),
                ('order_date', models.DateField(verbose_name='Data transakcji')),
                ('order_price', models.IntegerField(verbose_name='Kwota transakcji')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clients')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order_status')),
            ],
        ),
    ]
