# Generated by Django 4.1.7 on 2023-03-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order_status_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(default=1, max_length=50, verbose_name='VIN'),
            preserve_default=False,
        ),
    ]
