# Generated by Django 4.1.7 on 2023-03-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_car_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=17, verbose_name='VIN'),
        ),
    ]
