# Generated by Django 4.1.7 on 2023-03-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_car_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='nip',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='pesel',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='PESEL'),
        ),
    ]
