# Generated by Django 4.1.7 on 2023-04-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_contact_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.yes_no'),
        ),
    ]
