# Generated by Django 4.1.7 on 2023-03-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_clients_nip_alter_clients_pesel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='nip',
            field=models.IntegerField(blank=True, null=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='pesel',
            field=models.IntegerField(blank=True, null=True, verbose_name='PESEL'),
        ),
    ]
