# Generated by Django 4.1.7 on 2023-04-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_contact_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_mail', models.EmailField(max_length=100)),
                ('client_score', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('client_opinion', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rodo', models.BooleanField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
