# Generated by Django 4.1.7 on 2023-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_clients_nip_alter_clients_pesel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='id',
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
