# Generated by Django 4.1.7 on 2023-04-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_car_gear_alter_car_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Biały', 'Biały'), ('Szary', 'Szary'), ('Czarny', 'Czarny'), ('Srebrny', 'Srebrny'), ('Niebieski', 'Niebieski'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony'), ('Żółty', 'Żółty'), ('Brązowy', 'Brązowy'), ('Inny', 'Inny')], default=1, max_length=50, verbose_name='Kolor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('6', '6'), ('7 lub wiecej', '7 lub wiecej')], default=5, max_length=50, verbose_name='Liczba miejsc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Używany', 'Używany'), ('Nowy', 'Nowy')], default=2, max_length=50, verbose_name='Typ'),
            preserve_default=False,
        ),
    ]
