# Generated by Django 4.1.7 on 2023-04-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_car_color_car_seats_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2/3', '2/3'), ('4/5', '4/5')], default=0.8, max_length=50, verbose_name='Liczba drzwi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Używane', 'Używane'), ('Nowe', 'Nowe')], max_length=50, verbose_name='Typ'),
        ),
    ]
