# Generated by Django 4.1.7 on 2023-05-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_car_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOnSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_offer', models.BooleanField(default=False, verbose_name='Promocja')),
                ('new_price', models.IntegerField(blank=True, null=True, verbose_name='Nowa cena (PLN)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.car')),
            ],
        ),
    ]
